### ISSUE TITLE
File missing from pip install

### ISSUE THREAD

**Issue by austinjp** [Brobin/drf-generators#14]
Hi there.

The file `<path-to-python-site-packages>/drf_generators/management/__init__.py` is missing when installing drf-generators from pip, as described at http://brobin.me/blog/2015/4/13/how-to-quickly-write-an-api-in-django

This produces the following error:

```
$ python manage.py generate api --format modelviewset
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/django-app/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/user/django-app/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/django-app/lib/python2.7/site-packages/django/core/management/__init__.py", line 190, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/user/django-app/lib/python2.7/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.generate
```

It appears easily fixed by:

```
touch <path-to-python-site-packages>/drf_generators/management/__init__.py
```

After this, running `python manage.py generate api --format modelviewset` seems to run without any problems.

**Comment by Brobin** [comment]
I ran into this issue on another one of my django packages! I'll get a fix up right away.

**Comment by Brobin** [comment]
The new version is pushed to pypi. Thanks again for catching this!

**Comment by austinjp** [comment]
Excellent news, thanks for being so responsive! Took me a while to debug ;)

**Comment by Brobin** [comment]
Sorry for that. I hope the package is useful to you!

**Comment by austinjp** [comment]
No problem, looks good so far, I look forward to using it.
